Add: 로그인 기능 추가
minju1009/PuzzleAI-FE pull request #5
Opened 2022-05-05 10:55 UTC by minju1009

### PR Type
- [ ] 버그 수정
- [ ] 신규 기능
- [ ] 기타 (기타인 경우 내용 입력 :  ) 

### 해당 PR의 목적
- 로그인 기능 추가
   - 로그인 성공시 Asyncstorage에 토큰 저장
    - 앱 오픈시 로그인 state에 따라 유저에게 보여주는 화면 지정
### 해당 PR 사유
- 로그인 기능 추가

### 리뷰어가 중점적으로 봤으면 하는 부분
- `Context` 사용시 타입 지정에 관해 어려움을 겪었는데, 해당 부분을 맞게 적용한 것인지 확인 부탁드립니다.
   - `AuthContext`와 `AuthContextProvider`를 생성 후 export해서 사용하였습니다.
   - `index.js`에서 `Navigator`를 `AuthContextProvider`로 감싸주었습니다.
   - `Navigator`와 `Login` 컴포넌트에서 `AuthContext`를 불러와 사용시에 계속 오류가 나서`Type Assertion`을 통해 타입을 지정해주었습니다. 초기값을 `false`로 지정해주기 위해서는 <boolean>타입이 있어야 하지만, 사용시에는 `useState`를 사용해야 하기에 부득이하게 type assertion을 사용했는데 맞게 한 것인지 피드백 부탁드립니다!

2022-05-06 01:31 UTC, jasonkang14 requested changes
고생하셨습니다! 
`useReducer()`와 `AuthContextProvider`를 잘 사용하시면, 
api호출을 모두 provider에서 하고, api call 성공/실패 여부와 response로 넘어오는 데이터 들을 store에서 확인할 수 있을 것 같습니다. 공수가 너무 클 것 같으면 `setLoggedIn`만 `provider`에서 선언될 수 있도록 수정해주세요!

2022-05-06 01:31 UTC, jasonkang14 commented on src/AuthContext.tsx
> +export const AuthContext = createContext<AuthContextType | boolean>(false);
[createContext](https://reactjs.org/docs/context.html#reactcreatecontext)를 호출할 때 parameter로는 `defaultValue`가 사용됩니다.  `AuthContextType`에 선언한 타입은 `loggedIn`과 `setLoggedIn` 두개이니, 함수의 초기값도 같이 사용되어야 합니다.

2022-05-06 01:31 UTC, jasonkang14 commented on src/AuthContext.tsx
> +  const [loggedIn, setLoggedIn] = useState<boolean>(false);
context api를 사용할 때는 `useState()` 보다는 [useReducer](https://reactjs.org/docs/hooks-reference.html#usereducer)를 사용합니다. 왜 그런지 이유를 찾아서 전달 드리려고 했는데, 다시 보니 그냥 어떤 방식을 선호하냐의 차이인 것 같습니다 

값이 하나이니 state를 사용해도 될 것 같은데. 위에 `createContext()`를 호출할 때 `setState()`에 해당하는 함수의 초기값을 어떻게 선언해줄지는 솔직히 잘 모르겠습니다. 
`useReducer()`를 사용하면 일반 함수를 사용해서 store의 값을 변경할 수 있는데, 어쩌면 그래서 `useReducer()`가 더 많이 사용되는걸지도 모르겠네요. 

useReducer의 사용법은 [벨로퍼트 블로그](https://react.vlpt.us/basic/22-context-dispatch.htmlhttps://react.vlpt.us/basic/22-context-dispatch.html)에 자세히 나와있습니다.

2022-05-06 01:31 UTC, jasonkang14 commented on src/Navigator.tsx
> +  }, [setLoggedIn]);
여기는 dependency array를 비워두고, 최초 로딩에서만 token을 확인하는게 맞지 않을까요?

2022-05-06 01:31 UTC, jasonkang14 commented on src/Navigator.tsx
> +        setLoggedIn(true);
토큰이 있는 경우에 무조건 `setLoggedIn(true)`를 하기 보다는, 토큰이 실제 서버에서 발급한 토큰이 맞는지 확인하는 절차가 추가로 필요할 것 같습니다. 서버에도 api가 토큰을 확인하는 api가 추가되어야 할 것 같습니다.

2022-05-06 01:31 UTC, jasonkang14 commented on src/Navigator.tsx
> +            <RootStack.Screen
splash는 로그인 여부와 상관없이 접근할 수 있도록 변경되어야 할 것 같습니다.

2022-05-06 09:25 UTC, minju1009 commented on src/AuthContext.tsx
> +export const AuthContext = createContext<AuthContextType | boolean>(false);
`useReducer`로 변경하였습니다!

2022-05-06 09:26 UTC, minju1009 commented on src/AuthContext.tsx
> +  const [loggedIn, setLoggedIn] = useState<boolean>(false);
링크 걸어주신 벨로퍼트 블로그 보고 `useReducer` 사용으로 변경하였습니다!

2022-05-06 09:27 UTC, minju1009 commented on src/Navigator.tsx
> +  }, [setLoggedIn]);
다른 방법으로 변경해주었습니다!

2022-05-06 09:27 UTC, minju1009 commented on src/Navigator.tsx
> +        setLoggedIn(true);
미류님과 소통하여 해당 부분 추가하였습니다 :)

2022-05-06 09:35 UTC, minju1009 commented on src/Navigator.tsx
> +            <RootStack.Screen
만약 로딩 중이라면(토큰 확인 절차 진행 중) Splash 스크린이 보여지고, 로딩이 끝났다면(토큰 확인 절차 완료) 토큰 유무에 따라 스크린이 변경되도록 수정하였습니다!

2022-05-06 09:55 UTC, minju1009 commented
병진님! 주신 피드백 따라 아래와 같이 수정하였습니다 !
1. `useState`대신 `useReducer`로 변경한 후, API 호출도 Provider안에 넣어주었습니다.
2. 로딩 상태(토큰 유무확인 절차)에 따라 Splash screen이 user에게 먼저 보여진 후, 토큰 유무에 따라 navigator 추가 처리해 주었습니다.

2022-05-06 10:03 UTC, jasonkang14 approved these changes
고생하셨습니다! comment는 참고해주세요!

2022-05-06 10:03 UTC, jasonkang14 commented on src/AuthContext.tsx
> +  prevState: InitialState,
여기는 `state`라고 작성해주는 것이 일반적입니다

2022-05-06 10:03 UTC, jasonkang14 commented on src/AuthContext.tsx
> +type InitialState = {loggedIn: boolean; isLoading: boolean};
`type`은 `State`가 더 정확할 것 같습니다. 
`initialState`와 `state` 모두 `State`라는 Type을 갖게 되는 식으로요

2022-05-06 10:03 UTC, jasonkang14 commented on src/AuthContext.tsx
> +  const authContext = React.useMemo(
`console.log()`를 찍어봐야 알겠지만 여기는 react component와 다르게 re-render가 일어나지 않기 때문에 `useMemo()`를 사용하지 않아도 될 것 같습니다.

2022-05-06 10:03 UTC, jasonkang14 commented on src/AuthContext.tsx
> +      userState: userState,
`key`와 `value`가 같을 때는 `value`를 생략할 수 있습니다. 
```typescript
{
  userState,
  loggedIn: true
}

```

2022-05-06 10:03 UTC, jasonkang14 commented on src/Navigator.tsx
> +  if (userState.isLoading) {
👍

2022-05-06 10:03 UTC, jasonkang14 commented on src/screens/Login/index.tsx
> +    if (!email || !password) {
👍

2022-05-06 10:03 UTC, merged

2022-05-09 01:44 UTC, minju1009 commented on src/AuthContext.tsx
> +  prevState: InitialState,
해당 부분 `state`로 수정하였습니다!

2022-05-09 01:49 UTC, minju1009 commented on src/AuthContext.tsx
> +type InitialState = {loggedIn: boolean; isLoading: boolean};
`State`라는 type을 선언해주고, 초기값과 state모두 `State`라는 type을 가지도록 수정했습니다! 
```
type State = {loggedIn: boolean; isLoading: boolean};
type Action = {type: 'LOG_IN' | 'VALID_TOKEN' | 'LOADING_DONE'};

function reducer(state: State, action: Action): State {
  switch (action.type) {
    case 'LOADING_DONE':
      return {
```

2022-05-09 01:52 UTC, minju1009 commented on src/AuthContext.tsx
> +  const authContext = React.useMemo(
네, re-render일어나지 않는 것 확인했고, `useMemo()`삭제해주었습니다!

2022-05-09 01:54 UTC, minju1009 commented on src/AuthContext.tsx
> +      userState: userState,
넵, 해당부분 userState로 변경해주었습니다!