Add : VideoScreen UI 구현 및 getUserMedia로 localstream 가져오기
minju1009/PuzzleAI-FE pull request #7
Opened 2022-05-11 05:26 UTC by minju1009

### PR Type
- [ ] 버그 수정
- [ ] 신규 기능
- [ ] 기타 (기타인 경우 내용 입력 :  UI 구현) 

### 해당 PR의 목적
VideoScreen UI 구현 및 getUserMedia로 localstream 가져오기

### 해당 PR 사유
WebRTC 구현을 위한 UI 작업 및 stream확인

### 리뷰어가 중점적으로 봤으면 하는 부분
- UI 구현을 완료했으나, 아래와 같은 이슈 해결중에 있습니다. 
- 1,2번 타입오류의 경우 찾아보니 `  "@types/react-native-webrtc": "^1.75.5",`를 설치해주면 된다는 글을 봐서 설치를 해보았으나 해결이 되지 않고 있습니다. 
- 3번의 경우 원인을 계속 찾아봤으나, 찾기 어려워 혹시 어떤 키워드로 찾아보면 될지 여쭙습니다! 

1. `localStream`의 타입 지정을 `MediaStream`으로 해주었으나 계속 오류가 나는 이슈
```
const [localStream, setLocalStream] = useState<MediaStream>();
// 중략
.then(myStream => setLocalStream(myStream));
```
2. `RTCView`에 속성 지정시 타입 오류가 나는 이슈
<img width="410" alt="image" src="https://user-images.githubusercontent.com/90900882/167774741-93765f85-97b0-4280-b8e5-60f3acf0b697.png">

3. getUserMedia로 내 stream을 가져오는데, ios에서는 아예 검은 화면이 나오며, 안드로이드에서는 이상한 캐릭터가 보이는 이슈

<img width="200" alt="image" src="https://user-images.githubusercontent.com/90900882/167774519-f283d6ec-c1cb-4ce8-afe3-e3bd68741ae5.png">
<img width="200" alt="image" src="https://user-images.githubusercontent.com/90900882/167774558-61334aa6-175f-42ac-b7bf-a44962d8ef8f.png">

2022-05-11 09:18 UTC, jasonkang14 commented
1. `MediaStream`이 type인지 아닌지 확인이 필요합니다. 
2. iOS시뮬레이터와 안드로이드 에뮬레이터 모두 카메라가 없어서 그렇습니다. 제공해드린 테스트용 디바이스와 개인 휴대전화로 빌드하시면 카메라가 활성화 되는 것을 보실 수 있을거에요
 - 안드로이드에서 저 이상한 아이콘이 나오는 걸 보면 카메라가 정상적으로 작동할 것 같습니다.

2022-05-11 09:23 UTC, jasonkang14 requested changes
오디오 온/오프 아이콘 크기가 다른데 제플린 문제인가요?

2022-05-11 09:23 UTC, jasonkang14 commented on src/screens/VideoScreen/index.tsx
> +  const [localStream, setLocalStream] = useState<MediaStream>();
말씀하신 에러가 여기에 있을 것 같네요~ 
`MediaStream`이  type이 맞다면 `()` 여기에 아무런 값도 없기 때문에 에러가 발생하는 것이고, 
PR comment에 작성하신 것처럼 작성했다면, `MediaStream`이 type이 아니기 때문에 에러가 발생할 것 같습니다.

2022-05-11 09:23 UTC, jasonkang14 commented on src/screens/VideoScreen/index.tsx
> +  useEffect(() => {
`useEffect()`에서는 한가지 기능만 수행하는 것이 좋습니다. effect hook이 여러개여도 괜찮으니 따로 선언해주세요

2022-05-11 09:23 UTC, jasonkang14 commented on src/screens/VideoScreen/index.tsx
> +        streamURL={localStream && localStream.toURL()}
👍

2022-05-11 09:23 UTC, jasonkang14 commented on src/screens/VideoScreen/index.tsx
> +        mirror={true}
prop이 true이면 생략할 수 있습니다.  string은 {} 로 감싸주지 않아도 됩니다.
```typescript
<RTCView
  style={styles.removeVideo}
  objectFit='cover'
  mirror
  streamURL={localStream && localSTream.toURL()}
/>
```

2022-05-11 09:23 UTC, jasonkang14 commented on src/screens/VideoScreen/index.tsx
> +        style={styles.remoteVideo}
remoteVideo인데 왜 로컬스트림을 할당하나요?

2022-05-11 09:23 UTC, jasonkang14 commented on src/screens/VideoScreen/index.tsx
> +            setIsFront(prev => !prev);
이 방식으로 처리가 된다면 `isFront` 값이 바뀔 때마다 작동하는 effect hook이 필요합니다.

2022-05-11 09:23 UTC, jasonkang14 commented on src/screens/VideoScreen/index.tsx
> +            setVideoOn(prev => !prev);
오디오 비디오 토글도 값이 변경될 때 마다 작동하는 effect hook이 필요합니다.

2022-05-11 09:26 UTC, jasonkang14 commented
1,2번 타입오류의 경우 찾아보니 "@types/react-native-webrtc": "^1.75.5",를 설치해주면 된다는 글을 봐서 설치를 해보았으나 해결이 되지 않고 있습니다. 어떻게 하면 타입오류를 해결할 수 있을지요?

이걸 놓쳤네요. 
저기 레포에 직접 들어가보시면 에러가 왜 발생하는지 알 수 있으실거에요. 
만약 타입이 제대로 잘 선언이 되어있다고 한다면, `tsconfig.json`에서 type들의 위치를 참조할 수 있는 디렉토리를 정해주지 않아서입니다

2022-05-12 02:11 UTC, minju1009 commented on src/screens/VideoScreen/index.tsx
> +  const [localStream, setLocalStream] = useState<MediaStream>();
localStream에 들어가야 하는 값의 타입이 `Promise<MediaStream>`타입이라 이렇게 되도록 지정해주었습니다!

2022-05-12 02:11 UTC, minju1009 commented on src/screens/VideoScreen/index.tsx
> +  useEffect(() => {
네, 따로 선언될 수 있도록 분리하였습니다!

2022-05-12 02:12 UTC, minju1009 commented on src/screens/VideoScreen/index.tsx
> +        mirror={true}
해당 부분 자꾸 오류가 나서 이것저것 넣어보다가 ^^;;...이 부분도 타입지정해주어 해결하였습니다 :)

2022-05-12 02:13 UTC, minju1009 commented on src/screens/VideoScreen/index.tsx
> +        style={styles.remoteVideo}
fullscreen형태로 제대로 나오는지 보려고 임의로 넣어두고 테스트했습니다 :) 이런 부분은 헷갈리지 않도록 주석으로 표시하거나 PR 올릴때 삭제하겠습니다!!

2022-05-12 02:14 UTC, minju1009 commented on src/screens/VideoScreen/index.tsx
> +            setIsFront(prev => !prev);
`isFront`값이 바뀔때마다 기존의 stream을 중단하고 새로 받아오도록 수정해주었습니다!

2022-05-12 02:14 UTC, minju1009 commented on src/screens/VideoScreen/index.tsx
> +            setVideoOn(prev => !prev);
이 부분도 별도의 함수로 다시 작성해주었습니다!

2022-05-12 02:26 UTC, minju1009 commented
병진님, 자세한 코멘트 늘 감사드립니다!!

온/오프 버튼의 경우 제플린에서 다운받은 이미지를 동일한 속성을 사용하여 크기 설정해 주었는데, 버튼 크기가 말씀하신 대로 살짝 다르네요!
이부분 필요하다면 추가 수정하도록 하겠습니다.

추가로, 아래의 수정 사항 반영 완료하였습니다!
    - `MediaStream` 타입 및 `RTCView` 타입 정의하여 기존에 발생하던 타입 문제 해결 
    -   화면 전환, 카메라, 마이크 제어 버튼에 연결하는 함수 수정

2022-05-12 04:32 UTC, jasonkang14 approved these changes
LGTM

2022-05-12 04:32 UTC, jasonkang14 commented on src/screens/VideoScreen/index.tsx
> +  const handleAudio = () => {
굳굳 변수명도 잘 지정하셨네요 👍

2022-05-12 04:32 UTC, jasonkang14 commented on src/screens/VideoScreen/index.tsx
> +          (track: {enabled: boolean}) => (track.enabled = !track.enabled),
오 좋네요

2022-05-12 04:32 UTC, jasonkang14 commented on src/screens/VideoScreen/index.tsx
> +    localStream &&
앞에 `localStream &&` 처리 잘하셨네요. 화면에서 본인의 영상이 나오기전에 버튼을 클릭하면 에러가 발생하는 경우가 있거든요 👍

2022-05-12 04:32 UTC, jasonkang14 commented on tsconfig.json
> +    "typeRoots": ["node_modules/@types"]
잘처리하셨네요 💯

2022-05-12 04:33 UTC, merged

2022-05-12 05:05 UTC, minju1009 commented
휴가셔서 일부러 내일 말씀드리려고 조용히 있었는데, 괜히 번거롭게 해드린게 아닌가 몰라요😭✨
피드백 감사드립니다!! 🙇‍♀️🙏